# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Peter/Desktop/VivadoProjects/Verilog/SimpleFSM/SimpleFSM/Arty-A7-100-Master.xdc

# IP: ip/Blinker_Div/Blinker_Div.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Blinker_Div || ORIG_REF_NAME==Blinker_Div} -quiet] -quiet
