webtalk_init -webtalk_dir C:/Users/Peter/Desktop/VivadoProjects/Verilog/Clock_Div/clock_divider/clock_divider.sim/sim_1/behav/xsim/xsim.dir/divider_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jun  9 20:05:39 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "57cc9c48-fc9d-4342-8f82-71348cf275b0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6da9c028d0024cf4938a7ff45cfa92e9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "46" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 3800X 8-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3893 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6304_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3491705101 -regid "" -xml C:/Users/Peter/Desktop/VivadoProjects/Verilog/Clock_Div/clock_divider/clock_divider.sim/sim_1/behav/xsim/xsim.dir/divider_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Peter/Desktop/VivadoProjects/Verilog/Clock_Div/clock_divider/clock_divider.sim/sim_1/behav/xsim/xsim.dir/divider_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Peter/Desktop/VivadoProjects/Verilog/Clock_Div/clock_divider/clock_divider.sim/sim_1/behav/xsim/xsim.dir/divider_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
