# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Peter/Desktop/VivadoProjects/UART_IP/SourceFiles/constrs_1/new/consfile.xdc

# IP: C:/Users/Peter/Desktop/VivadoProjects/UART_IP/SourceFiles/sources_1/ip/rx_fifo/rx_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_fifo || ORIG_REF_NAME==rx_fifo} -quiet] -quiet

# IP: ip/Sample_Clock/Sample_Clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sample_Clock || ORIG_REF_NAME==Sample_Clock} -quiet] -quiet

# IP: ip/Baud_Clock/Baud_Clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Baud_Clock || ORIG_REF_NAME==Baud_Clock} -quiet] -quiet
