# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/conts.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UART_Controller_0_1/design_1_UART_Controller_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UART_Controller_0_1 || ORIG_REF_NAME==design_1_UART_Controller_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UART_Controller_0_1/sources_1/ip/rx_fifo/rx_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rx_fifo || ORIG_REF_NAME==rx_fifo} -quiet] -quiet

# IP: c:/Users/Peter/Desktop/VivadoProjects/UARTTest/Users/Peter/Desktop/VivadoProjects/UART_IP/UART_IP.srcs/sources_1/ip/Sample_Clock/Sample_Clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sample_Clock || ORIG_REF_NAME==Sample_Clock} -quiet] -quiet

# IP: c:/Users/Peter/Desktop/VivadoProjects/UARTTest/Users/Peter/Desktop/VivadoProjects/UART_IP/UART_IP.srcs/sources_1/ip/Baud_Clock/Baud_Clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Baud_Clock || ORIG_REF_NAME==Baud_Clock} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_0 || ORIG_REF_NAME==design_1_system_ila_0_0} -quiet] -quiet

# Block Designs: bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c || ORIG_REF_NAME==bd_f60c} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] -quiet

# XDC: bd/design_1/ip/design_1_UART_Controller_0_1/sources_1/ip/rx_fifo/rx_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rx_fifo || ORIG_REF_NAME==rx_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_UART_Controller_0_1/constrs_1/new/consfile.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_UART_Controller_0_1 || ORIG_REF_NAME==design_1_UART_Controller_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c_ooc.xdc

# XDC: bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
