set_property SRC_FILE_INFO {cfile:C:/Users/Peter/Desktop/VivadoProjects/project_1/project_1.srcs/constrs_1/new/constrain.xdc rfile:../../../project_1.srcs/constrs_1/new/constrain.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E1 [get_ports LED]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A8 [get_ports Switch]
